### PR TITLE
Fixes #264

### LINKED ISSUE #264: synchronized on method synExit never trigger!
Hi @jbachorik 
version 1.3.8.3
my test class:

`import java.io.IOException;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

public class BtraceSynCheckTest {

	public static synchronized void test() {
		System.out.println("call test");
	}
	
	public static void test2() {
		synchronized (BtraceSynCheckTest.class) {
			System.out.println("call test2 block");
		}
	}

	public static void main(String[] args) {

		try {
			Thread.sleep(30000);
		} catch (InterruptedException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	
		new NewClz().myTest();
		
		test2();
				
	        test();

	}
	
	static class NewClz {
		
		public synchronized void myTest() {
			System.out.println("call myTest block");
		}
	}

}`

btrace script:
`@OnMethod(
			 clazz="/com\\.baitian\\.test\\.test\\..*/",
			 method="/.*/",
			 location=@Location(Kind.SYNC_EXIT)
	 )
	public static void onSyncExit() {
		println("before synchronized exit");
	}`

but the test()  and myTest() after called exit, never println the infos("before synchronized exit")!
Is it someting wrong with the com.sun.btrace.runtime.instr.SynchronizedInstrumentor.java

### PR DESCRIPTION
**Pull request by yanfeipeng**
Fix bug synchronized on method synExit never trigger! #264

---
This change is [Reviewable](https://reviewable.io/reviews/btraceio/btrace/268)

### CODE REVIEW

**Comment by yanfeipeng** [comment]
When i gradlew build my local btrace project, I aslo find so many error: [FallThrough] Switch case may fall through!
I need to fix it one by one, and make sure i can build success!

File: src/share/classes/com/sun/btrace/runtime/instr/SynchronizedInstrumentor.java [hunk 1]
```diff
@@ -74,6 +74,18 @@ public void visitInsn(int opcode) {
         } else if (opcode == MONITOREXIT) {
             onBeforeSyncExit();
         }
+        switch (opcode) {
```
Comment (yardus) [inline src/share/classes/com/sun/btrace/runtime/instr/SynchronizedInstrumentor.java]: I think it would be better to go up the class hierarchy and make `ErrorReturnInstrumentor` to extend `MethodReturnInstrumentor` which it should. Then, instead of repeating the same switch statement you could just call `super.visitInsn(opcode)` and the effect should be the same.

Comment (yanfeipeng) [inline src/share/classes/com/sun/btrace/runtime/instr/SynchronizedInstrumentor.java]: Yes, but do like that,  it would change the ErrorReturnInstrumentor  logic of ERROR KIND Type, it is OK?

Comment (yardus) [inline src/share/classes/com/sun/btrace/runtime/instr/SynchronizedInstrumentor.java]: I think that would be correct - `ErrorReturnInstrumentor` should handle exit either by error or by 'return' opcode. The current situation is erroneous - `onMethodReturn` will never be called in the `ErrorReturnInstrumentor`, missing the expected exit points.

Comment (yanfeipeng) [inline src/share/classes/com/sun/btrace/runtime/instr/SynchronizedInstrumentor.java]: Yes, it would be correct in the exception situation, but if the method runs well, it would trigger onMethodReturn. So if ErrorReturnInstrumentor extends MethodReturnInstrumentor, it need to overwrite onMethodReturn by using empty method, is that right?

Comment (yardus) [inline src/share/classes/com/sun/btrace/runtime/instr/SynchronizedInstrumentor.java]: Yes, either overriding with an empty method sounds good.

**Comment by jbachorik** [comment]
Thanks again for contributing!
